
# Default values for sensu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

storageClass: default

gateway:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

sensu:
  image:
    repository: roger21gm/sensu
    tag: 6.6.4

api:
  service: 
    type: NodePort
    nodePort: 31333
  
transport:
  service: 
    type: NodePort
    nodePort: 31334

ui:
  service: 
    type: NodePort
    nodePort: 31335
  image:
    repository: roger21gm/sensu-go-ui
    tag: latest

service:
  type: NodePort
  nodePort: 30333

etcd:
  global:
    storageClass: default
  persistence:
    size: 8Gi
  autoCompactionMode: "revision"
  autoCompactionRetention: 2
  auth:
    rbac:
      create: false
    



