---
# standalone etcd w/ sensu-agent sidecar
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sensu.fullname" . }}-etcd
  labels:
    {{- include "sensu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "sensu.selectorLabels" . | nindent 6 }}
      app: sensu-etcd
  serviceName: sensu-etcd
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: sensu-etcd
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 20Gi
  template:
    metadata:
      labels: {{- include "sensu.selectorLabels" . | nindent 8 }}
        app: sensu-etcd
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: sensu-etcd
        persistentVolumeClaim:
          claimName: sensu-etcd
      - name: sensu-asset-server-ca-cert
        secret:
          secretName: sensu-asset-server-ca-cert
          defaultMode: 256
          optional: true
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.3.22
        command: [
          "/usr/local/bin/etcd",
          "--data-dir", "/var/lib/etcd",
          "--initial-cluster-state", "new",
          "--name", "sensu",
          "--listen-client-urls", "http://0.0.0.0:2379",
          "--advertise-client-urls", "http://$(ETCD_NAME):2379",
        ]
        env:
        - name: ETCD_NAME
          value: {{ include "sensu.fullname" . }}-etcd-headless
        volumeMounts:
        - name: sensu-etcd
          mountPath: /var/lib/etcd
        ports:
        - protocol: TCP
          containerPort: 2379
        - protocol: TCP
          containerPort: 2380
        resources:
          requests:
            memory: 2048M
            cpu: 1.0
          limits:
            memory: 4096M
            cpu: 2.0
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          exec:
            command:
            - wget
            - --no-check-certificate
            - -q
            - -O-
            - http://127.0.0.1:2379/health