---
# load balancer for cluster-external access to sensu-backends (web + API + transport)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensu.fullname" . }}-sensu-gateway
  labels:
    {{- include "sensu.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sensu.selectorLabels" . | nindent 4 }}
    app: sensu
  type: {{ .Values.service.type }}
  ports:
  - name: sensu-api
    protocol: TCP
    port: 8080
    targetPort: 8080
{{ if (and (eq .Values.api.service.type "NodePort") (not (empty .Values.api.service.nodePort))) }}
    nodePort: {{.Values.api.service.nodePort}}
{{ end }}
  - name: sensu-transport
    protocol: TCP
    port: 8081
    targetPort: 8081
{{ if (and (eq .Values.transport.service.type "NodePort") (not (empty .Values.transport.service.nodePort))) }}
    nodePort: {{.Values.transport.service.nodePort}}
{{ end }}
  - name: sensu-webui
    protocol: TCP
    port: 80
    targetPort: 3000
{{ if (and (eq .Values.web.service.type "NodePort") (not (empty .Values.web.service.nodePort))) }}
    nodePort: {{.Values.web.service.nodePort}}
{{ end }}