apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensu.fullname" . }}-ui
  labels:
    {{- include "sensu.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "sensu.selectorLabels" . | nindent 6 }}
      app: sensu-ui
  template:
    metadata:
      labels: {{- include "sensu.selectorLabels" . | nindent 8 }}
        app: sensu-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - yarn
            - node
            - scripts
            - serve
          env:
            - name: API_URL
              value: http://{{ include "sensu.fullname" . }}-sensu-gateway:8080
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          name: sensu-ui
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 2048M
              cpu: 1.0
            limits:
              memory: 4096M
              cpu: 2.0
            
      restartPolicy: Always
